name: Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest
      - run: mdbook build
      - uses: actions/upload-pages-artifact@main
        with:
          path: book
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
